{% set name = "scvelo" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scvelo-{{ version }}.tar.gz
  sha256: 9383a8712f81f0f2d2f1bddcfc81889ede06a0027de537b5b9af83ed821390c7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - anndata >=0.7.5
    - scanpy >=1.5
    - loompy >=2.0.12
    - umap-learn >=0.3.10
    - numba >=0.41.0
    - numpy >=1.17
    - pandas >=1.1.1,!=1.4.0
    - scipy >=1.4.1
    - scikit-learn >=0.21.2
    - matplotlib-base >=3.3.0

test:
  imports:
    - scvelo
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/theislab/scvelo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: RNA velocity generalized through dynamical modeling
  description: |
    A scalable toolkit for RNA velocity analysis in single-cells.
  doc_url: https://scvelo.readthedocs.io
  dev_url: https://github.com/theislab/scvelo

extra:
  recipe-maintainers:
    - WeilerP
